export const FETCH_SUPPLEMENTS = "FETCH_SUPPLEMENTS";
export const LOAD_SUPPLEMENTS = "LOAD_SUPPLEMENTS";
export const FETCH_SUPPLEMENT_LOGS = "FETCH_SUPPLEMENT_LOGS";
export const LOAD_SUPPLEMENT_LOGS = "LOAD_SUPPLEMENT_LOGS";
