export const FETCH_SUPPLEMENTS = "FETCH_SUPPLEMENTS";
export const LOAD_SUPPLEMENTS = "LOAD_SUPPLEMENTS";
export const FETCH_SUPPLEMENT_LOGS = "FETCH_SUPPLEMENT_LOGS";
export const LOAD_SUPPLEMENT_LOGS = "LOAD_SUPPLEMENT_LOGS";
export const FETCH_EDIT_SUPPLEMENT_LOGS = "FETCH_EDIT_SUPPLEMENT_LOGS";
export const LOAD_EDIT_SUPPLEMENT_LOGS = "LOAD_EDIT_SUPPLEMENT_LOGS";
export const FETCH_ADD_MISSED_SUPPLEMENT_LOGS =
  "FETCH_ADD_MISSED_SUPPLEMENT_LOGS";
export const LOAD_ADD_MISSED_SUPPLEMENT_LOGS =
  "LOAD_ADD_MISSED_SUPPLEMENT_LOGS";
